services:
  - type: web
    name: primermvc
    runtime: docker
    plan: free
    rootDir: primerMvc
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: DB_HOST
        fromDatabase:
          name: primermvc-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: primermvc-db
          property: port
      - key: DB_NAME
        fromDatabase:
          name: primermvc-db
          property: database
      - key: DB_URL
        value: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
      - key: DB_USERNAME
        fromDatabase:
          name: primermvc-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: primermvc-db
          property: password

databases:
  - name: primermvc-db
    plan: free
    databaseName: primermvc
    user: primermvc
